version: '3'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports: 
      - "3000:3000"
    volumes:
      - /frontend/node_modules
      - .:/frontend
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /frontend/node_modules
      - .:/frontend
    command: ["npm", "run", "test"]
